In [ ]:
# 추천자료 
# - https://www.youtube.com/watch?v=SMpPaSpCaAo
# - http://www.deeplearning.net/tutorial/index.html
# - git clone https://github.com/lisa-lab/DeepLearningTutorials.git

In [ ]:
# 실전 Theano

In [1]:
%matplotlib inline

# pip install Theano

import numpy as np
import matplotlib.pyplot as plt
import theano
import theano.tensor as T

In [2]:
# Let's Do Some Hasking First
# 1. Symbolic Variables
# No particular value for x, y, z
# Representing relationship between numbers
x = T.scalar()
y = T.scalar()
z = x + y

In [3]:
# "compiles" a function ftnSum(Resuable!)
# 실제 실행하면 약간 멈칫한다. 즉 실제 C 컴파일이 일어난다.
# 그리고 이제부터는 재사용가능해진다.
# inputs의 인자는 리스트다. 심볼릭 variable 리스트를 받는다.
# output 인자는 결과 심볼릭 variable
# 자동으로 최적화 일어남(알아서 병렬처리 신경써준다)
# GPU에서 할지, CPU 여러개 병렬로 할지는 
# theano 실행하기 전에 - 외부에서 커맨드라인으로 theano의 설정으로 
# 환경설정을 해주면 된다.
# 그럼 알아서 해준다.
ftnSum = theano.function(inputs=[x, y], outputs=z)

INFO (theano.gof.compilelock): Waiting for existing lock by process '1502' (I am process '12803')
INFO:theano.gof.compilelock:Waiting for existing lock by process '1502' (I am process '12803')
INFO (theano.gof.compilelock): To manually release the lock, delete /Users/moodern/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lock_dir
INFO:theano.gof.compilelock:To manually release the lock, delete /Users/moodern/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '1502' (I am process '12803')
INFO:theano.gof.compilelock:Waiting for existing lock by process '1502' (I am process '12803')
INFO (theano.gof.compilelock): To manually release the lock, delete /Users/moodern/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/lock_dir
INFO:theano.gof.compilelock:To manually release the lock, delete /Users/moodern/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64/l

In [4]:
print(ftnSum(3,4)) 

7.0


In [5]:
# Data Types
x = T.scalar() # Default
x = T.iscalar() # int32
x = T.lscalar() # int64
x = T.dscalar() # float64

In [6]:
# default data type can be check by
print(theano.config.floatX)

float64


In [7]:
# A symbolic varible can have various dimensions
x = T.scalar() # 0-D
x = T.vector() # 1-D
x = T.matrix() # 3-D
x = T.tensor4() # 4-D

In [8]:
x = T.matrix()
y = T.matrix()
z = T.dot(x, y)

In [9]:
ftnSum_mat = theano.function([x, y], z)

In [10]:
print(ftnSum_mat(3,4)) # 입력값이 매트릭스가 아니다.

TypeError: ('Bad input argument to theano function at index 0(0-based)', 'Wrong number of dimensions: expected 2, got 0 with shape ().')

In [13]:
a = np.random.random((3,3))
a

array([[ 0.62691313,  0.77313606,  0.40112699],
       [ 0.57934803,  0.90520576,  0.45126854],
       [ 0.40031673,  0.31586405,  0.88877981]])

In [14]:
b = np.random.random((3,3))
b

array([[ 0.24364377,  0.77271438,  0.19895373],
       [ 0.8778745 ,  0.12743202,  0.28885663],
       [ 0.50680709,  0.55663208,  0.55975008]])

In [15]:
print(ftnSum_mat(a,b))

[[ 1.03475392  0.80622724  0.57258304]
 [ 1.16451769  0.81421329  0.62933573]
 [ 0.82526359  0.84430504  0.6683785 ]]


In [16]:
# For GPU, Theano supports 32bit float ONLY!
# Python automatically uses 64bit float
# We need to cast it manually
a = np.asarray(np.random.random((3,3)),
               dtype=theano.config.floatX)
b = np.asarray(np.random.random((3,3)),
               dtype=theano.config.floatX)
print(a, b, ftnSum_mat(a,b))

(array([[ 0.87293819,  0.95203566,  0.63113701],
       [ 0.83719607,  0.62026681,  0.06803089],
       [ 0.43213324,  0.32649747,  0.99109693]]), array([[ 0.41248065,  0.94015006,  0.83861041],
       [ 0.47695259,  0.72344934,  0.65491579],
       [ 0.69928108,  0.58633644,  0.73556436]]), array([[ 1.25548816,  1.87950108,  1.81980013],
       [ 0.68873776,  1.27571054,  1.15834497],
       [ 1.02702575,  1.22359072,  1.30523536]]))


In [ ]:
# 1. data types를 잘 파악하라(int, float ..)
# 2. dimensions에 주의하라(scalar, vector, matrix)
# 3. float32를 써라 

In [ ]:
# Shared Variables

# Python Variables : Have a specific value
# Theano Symbolic Variables : Are empty slots for computation
# Shared Variables : Are slots for computation
#                    and have a specific value
#                    Whose values are stored in GPU memory

# Python Variables ------- Theano Symbolic Variables
#                    | 
#                    V
#           Shared Variables

In [17]:
# You can easily create shared variables
a = np.array([[1,2],[3,4]], dtype=theano.config.floatX)
x = theano.shared(a)

# (It seems) data is sent to GPU memory at th moment 

In [18]:
# Retrieve or update its stored values
print(x.get_value())
x.set_value(x.get_value()+1)
print(x.get_value())

[[ 1.  2.]
 [ 3.  4.]]
[[ 2.  3.]
 [ 4.  5.]]


In [21]:
# Shared Variales - Complicatios

# 1. "Borrowing" : Making a soft copy
a = np.array([[1,2],[3,4]], dtype=theano.config.floatX)
x_1 = theano.shared(a)  # default : False
x_2 = theano.shared(a, borrow=True)

# "borrow=True" is generally recommended
# - Memory saving(not GPU's, unfortunately)
# - Faster code

# Keep that it is a soft copy
# - Change a, change x_2

In [22]:
# 2. Shared variables can't be inputs or ouputs
# They can only be the intermediates
a = np.array([[1,2],[3,4]], dtype=theano.config.floatX)
x = theano.shared(a)
y = x ** 2
ftnShared = theano.function([x], y)

TypeError: Cannot use a shared variable (<TensorType(float64, matrix)>) as explicit input. Consider substituting a non-shared variable via the `givens` parameter

In [ ]:
# II. Basic Funtions

# Theano provides predefined deep learning related functions !

# Multi Layer Perceptron :
# - T.nnet.sigmoid()
# - T.nnet.categorical_crossentropy()
# - T.nnet.softmax()

# Convolutional Neural Net :
# - T.nnet.conv.conv2d()
# - T.signal.downsample.max_pool_2d()
# - and a few more..complicated ..

In [ ]:
# III. Optimization

In [30]:
# Symbolic Differentiation
# diff(x^2) => 2x

x = T.scalar()
y = x ** 2
diff = theano.function([x], T.grad(y, [x]))

# Function to differentiate (Objective function)
# - Should be scalar
# Differentiating variable
# - Can be many
# Outpug of T.grad() is a list

In [31]:
# Outpug of T.grad() is a list
diff(3)

[array(6.0)]

In [34]:
# 결과가 리스트로 나오는게 싫으면
diff = theano.function([x], T.grad(y, [x])[0])
diff(3)

array(6.0)

In [36]:
# Evaluate & Update

x = T.scalar()
w = theano.shared(np.array(3, dtype=theano.config.floatX)
                  ,borrow=True)

In [37]:
obj = (1 - x*w)**2 # our objective
                   # x(데이터)에 w(가중치)를 곱해서 그 결과를 1에 가깝게
                   # 만들고 싶다. 최적화 목표.

In [39]:
learn_w = (w, w-0.1*T.grad(obj,w))
# x로부터, obj를 계산해서, 그 값으로 update를 계산
# x -> obj -> updates
# input : x
# output : obj
# updates : updates
learn = theano.function([x], obj, updates=[learn_w])

# "updates" arguments
# - A list of tuples
# - [(before, after), (before, after), ...]

In [40]:
# 학습
learn(2)

array(25.0)

In [ ]:
# Theano를 이용한 딥러닝